# Generated by Django 3.1.5 on 2021-02-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoolToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(default='26578e31f3f009b538ec28e2bbb92368', max_length=50)),
                ('status', models.CharField(choices=[('A', 'Alive'), ('B', 'Busy')], max_length=1)),
                ('timeStatus', models.DateField()),
            ],
        ),
    ]
