# Generated by Django 3.1.5 on 2021-02-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooltoken',
            name='timeStatus',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pooltoken',
            name='token_key',
            field=models.CharField(default='34dfc534729b28479e6c0d41291be1a9', max_length=50),
        ),
    ]
